
[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.12"

[[dependency]]
org = "ballerinax"
name = "googleapis_calendar"
version = "0.1.3"

[[dependency]]
org = "ballerinax"
name = "googleapis_gmail"
version = "0.99.4"

[[dependency]]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.6"

#[[dependency]]
#org = "ballerinax"
#name = "postgresql"
#version = "0.1.0"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.5"

[[dependency]]
org = "ballerinax"
name = "slack"
version = "0.9.6"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.6"
